version: '3.9'
services:
  nginx:
    image: '${NGINX_IMAGE}'
    container_name: '${NGINX_CONTAINER_NAME}'
    hostname: '${NGINX_HOSTNAME}'
    restart: always
    environment:
      TZ: '${TZ}'
    volumes:
      - ./src/conf.d:/etc/nginx/conf.d
      - ./src/data/:/etc/nginx/data
      - ./src/nginx.conf:/etc/nginx/nginx.conf
      - ./src/default.conf:/etc/nginx/default.conf
      - ./var/cache/:/etc/nginx/cache/
      - ./var/log/:/var/log/nginx/
    ports:
      - '${NGINX_SERVER_HTTP_PORT:-80}:80'
      - '${NGINX_SERVER_HTTPS_PORT:-443}:443'

  mariadb:
    image: "${MARIADB_IMAGE}"
    container_name: "${MARIADB_CONTAINER_NAME}"
    hostname: "${MARIADB_HOSTNAME}"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "${MARIADB_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${MARIADB_DATABASE}"
      TZ: "${TZ}"
    volumes:
      - ./storage/mariadb:/var/lib/mysql
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-p${MARIADB_ROOT_PASSWORD}"
        ]
      retries: 3
      timeout: 5s

  redis:
    image: "${REDIS_IMAGE}"
    container_name: "${REDIS_CONTAINER_NAME}"
    hostname: "${REDIS_HOSTNAME}"
    restart: always
    command: redis-server --requirepass "${REDIS_PASSWORD}"
    environment:
      TZ: "${TZ}"
    volumes:
      - ./storage/redis:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      retries: 3
      timeout: 5s

  minio:
    image: "${MINIO_IMAGE}"
    container_name: "${MINIO_CONTAINER_NAME}"
    hostname: "${MINIO_HOSTNAME_NAME}"
    restart: always
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      TZ: '${TZ}'
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    volumes:
      - ./storage/minio:/data/minio
    command: minio server /data/minio --console-address ":9001"
    healthcheck:
      test:
        [
          "CMD",
          "curl",
          "-f",
          "http://localhost:9000/minio/health/live"
        ]
      retries: 3
      timeout: 5s

  phpmyadmin:
    image: "${PHPMYADMIN_IMAGE}"
    container_name: "${PHPMYADMIN_CONTAINER_NAME}"
    hostname: "${PHPMYADMIN_HOSTNAME}"
    restart: always
    environment:
      PMA_HOST: "${MARIADB_HOSTNAME}"
      PMA_PMADB: phpmyadmin
      UPLOAD_LIMIT: 30000m
      TZ: "${TZ}"

  meilisearch:
    image: "${MEILISEARCH_IMAGE}"
    container_name: "${MEILISEARCH_CONTAINER_NAME}"
    hostname: "${MEILISEARCH_HOSTNAME}"
    environment:
      MEILI_HTTP_ADDR: 0.0.0.0:80
      MEILI_MASTER_KEY: "${MEILISEARCH_MASTER_KEY}"
      TZ: '${TZ}'
    volumes:
      - ./storage/meilisearch:/data.ms
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--no-verbose",
          "--spider",
          "http://localhost:7700/health"
        ]
      retries: 3
      timeout: 5s

  mailhog:
    image: "${MAILHOG_IMAGE}"
    container_name: "${MAILHOG_CONTAINER_NAME}"
    hostname: "${MAILHOG_HOSTNAME}"
    environment:
      TZ: '${TZ}'
      MH_MAILDIR_PATH: /home/mailhog
      MH_STORAGE: maildir
      MH_UI_BIND_ADDR: 0.0.0.0:80
    volumes:
      - ./storage/mailhog:/home/mailhog

networks:
  default:
    external: true
    name: '${APP_DOCKER_NETWORK}'